### ISSUE TITLE
HTML5

### ISSUE THREAD

**Issue by sixtyfive** [gurgeous/sinew#10]
So I talked to the Nokogiri people and it turns out that they have problems getting HTML5 support out of the underlying libxml. The only reliable way right now is to use [nokogumbo](https://github.com/rubys/nokogumbo), which uses Google's gumbo instead. Is there anything that would speak against changing sinew to use that?

**Comment by gurgeous** [comment]
I just released Sinew 2, which is a different animal in some ways. Can you reopen this if you are still interested in nokogumbo? Happy to experiment at some point. :)

**Comment by sixtyfive** [comment]
Thanks Adam, but I've long since moved on from that research project where we were using Sinew. All the best with Sinew 2! :-)

**Comment by gurgeous** [comment]
Sinew is in a long orbit. Every few years it comes back around and I need it again for more projects... :) Have fun!
