### ISSUE TITLE
How to get rid of the transliteration magic?

### ISSUE THREAD

**Issue by sixtyfive** [gurgeous/sinew#7]
Hi, first off, thanks for a great gem! I'm trying to do some work with Arabic websites and was already able to put the basics together following the docs and examples. Unfortunately, the CSV file contains no Arabic characters at all. E.g., the name of the American state secretary John Kerry, in Arabic "كيري" shows up at "kyry", which is entirely unusable for most scientific purposes. Apparently Sinew got the text off the website just fine, but it's applying some sort of unwanted transliteration to it. Could you give me a hint as to how I could have the original Arabic text (in UTF-8 if at all possible) written to the CSV instead?

**Comment by gurgeous** [comment]
Yes, sinew by default runs the HTML through tidy to make parsing easier. But that might trash your HTML in some cases.

Instead of using the `html` variable in your sinew file, try using `raw` instead - that's the raw, untidied HTML.

**Comment by sixtyfive** [comment]
That'd be a shame as I love the cleaning up tidy does in the document. Writing "كيري" as "kyry" is an _actual_ form of transliteration used to write Arabic word in English letters, so this seems to be an actual feature that someone actually implemented and I'd find it curious if it couldn't be turned off. Also, it wouldn't make any sense for you to only run tidy **after** the document has already been handed to Nokogiri for parsing. Here's my code:

```
noko.css('.right_area_container .main_area').each do |a|
  row = {regime: 'first'} 
  row[:url] = a.at_css('.header a')[:href]
  row[:headline] = a.at_css('.header a').text
  row[:summary] = a.at_css('.summary_area .summary_p').text
  puts row # Everything fine here!
  csv_emit(row) # All Arabic letters have been transliterated in the CVS...
end
```

**Comment by gurgeous** [comment]
Ah, I see. I think the problem is the normalization that sinew does when emitting rows. See:

https://github.com/gurgeous/sinew/blob/master/lib/sinew/main.rb#L168

Stuff like `convert_accented_html_entities`, `unent`, and `to_ascii` will not be helpful in your case, though this fixes many other problems with common usage. Maybe we need a command line flag to turn off normalization, or at least the unhelpful kinds in your case?

**Comment by sixtyfive** [comment]
Ah, thank you for the link! I was able to play around a bit now and it seems that indeed `.to_ascii` is where this happens:

```
main » require 'stringex'
=> true
main » "السلام عليكم".to_ascii
=> "lslm 'lykm"
```

A command line flag might work, sure, but I think some sort of option inside of the recipe would make more sense, since that's where all the information about the site being processed is kept. Language and writing system to me are part of that information. Just my two cents though :)

**Comment by sixtyfive** [comment]
By the way, where does `TextUtil` come from?

```
main » require "nokogiri" # must be loaded before awesome_print
=> false
main » require "awesome_print"
=> true
main » require "cgi"
=> false
main » require "csv"
=> false
main » require "htmlentities"
=> false
main » require "stringex"
=> false
main » TextUtil.unent "السلام عليكم"
NameError: uninitialized constant TextUtil
```

**Comment by gurgeous** [comment]
Certainly. Usage of sinew is pretty low so it's probably not worth a refactor. Perhaps just another option for `csv_emit`?

**Comment by sixtyfive** [comment]
`sinew/main.rb:86-98`, found it. I'm headed for bed now but might give it a shot tomorrow. Would be my first time changing someone else's code and making a pull request from it, though, so bear with me!
