### ISSUE TITLE
Sinew is Ruby but how exactly?

### ISSUE THREAD

**Issue by sixtyfive** [gurgeous/sinew#8]
Trying to do something that might not have been part of the plan:

```
def get_article_body(url)
  get url
  noko.at_css('article').text
end

def get_list_of_articles(url)
  get url
  noko.css('.articles').each do |div|
    path = div.at_css('.header a')[:href]
    row[:url] = path
    row[:body] = get_article_body("#{url}/#{path}")
    csv_emit(row)
  end
end

get_list_of_articles("http://www.domain.tld")
```

Unfortunately only the first call to `get` works, after that nothing seems to happen anymore. Am I going about this wrong or is it just not supported?

**Comment by gurgeous** [comment]
Is it hanging? Crashing? Put some debug printouts in there. Running --verbose helps too.

**Comment by sixtyfive** [comment]
Sorry, I didn't express myself correctly. So using `get` inside custom methods seems to be working fine. The problem seems to be with Nokogiri's CSS selectors not catching onto anything inside of an `<article>`, for whatever reason. I guess I should talk to them about that.
